### ISSUE TITLE
The website cannot be reached

### ISSUE THREAD

**Issue by ProCode-Software** [diekus/OneUI-CSS#66]
OneUIWeb.dev does not work anymore. In my browser, it says that the page can't be reached. May you please fix this?

**Comment by LightslicerGP** [comment]
I'm pretty sure since this is so old, having bandwidth usage to that site is pointless today so they are getting rid of it.


Although, I am working on a new version of it that will have just 1 file to import, that allows usage of oneui in web browsers

I have an example site at oneuiweb.netlify.app, but it's still a WIP

**Comment by youngsoo1-Kim** [comment]
Dear @ProCode-Software and @LightslicerGP 
Hi
First of all, Sorry for the late reply
Our https://oneuiweb.dev/ has been reactivated a while ago (This site is currently activating sequentially, and it will take up to an hour.)
Please visit again
Thank you!

**Comment by LightslicerGP** [comment]
Ah okay, thanks!
